### ISSUE TITLE
Source code organisation

### ISSUE THREAD

**Issue by jdemeyer** [malb/signal.pyx#7]
What's the point of the `src` directory? It seems it only makes your `setup.py` more complicated. I would move `scripts` and `signals_pyx` to the root of the package.

**Comment by vbraun** [comment]
Also, `signals_pyx` is imho terrible... File extensions on package names? Why not a namespace package `sage.interrupt`? Or anything with interrupt in the name.

**Comment by jdemeyer** [comment]
Why "`sage.`"? This won't be Sage-specific at all.

**Comment by jdemeyer** [comment]
> Or anything with interrupt in the name.

On sage-devel, I proposed to use "signals" instead of "interrupt" because the macros are called `sig_on` and `sig_off` and because this package deals with signals than just `SIGINT`.

**Comment by malb** [comment]
To discuss names, please see #3.

**Comment by malb** [comment]
To explain the `src` subdirectory. It makes sense especially for Cython projects. Otherwise, when you run Python from the top level of your project then you'll have trouble doing a `from project import *` because Python will look for it in current directory and will fail. See, e.g. https://hynek.me/articles/testing-packaging/

**Comment by jdemeyer** [comment]
OK, I'm convinced.
